#=======================================================
#Config Version: 4.2(Please Don't change this version)
#=======================================================
#Plugin Author: Refrac
#=======================================================
#Original Author: BGHDDevelopment
#=======================================================
#Plugin Page: https://www.spigotmc.org/resources/54528/
#=======================================================
#Permission: ustaffmode.update
Update:
  Enabled: true
#Enables if there is a message on-join when the plugin is outdated.
#=======================================================  
Messages: 
  Prefix: '&6&lULTIMATESTAFFMODE'
  MainMenu: '&7Returned To The Main Menu!'
#=======================================================
#Gamemode Menu Messages  
#Permission: ustaffmode.gamemode
  GamemodeMenu: '&7Opened The Gamemodes Menu!'
  Creative: '&7Gamemode changed to Creative!' 
  Survival: '&7Gamemode changed to Survival!' 
  Spectator: '&7Gamemode changed to Spectator!'
  Adventure: '&7Gamemode changed to Adventure!'
#=======================================================
#Time Menu Messages    
#Permission: ustaffmode.time
  TimeMenu: '&7Opened The Time Menu!'  
  TimeSixAM: '&7Time Changed To &e6AM&7!'
  TimeSevenAM: '&7Time Changed To &e7AM&7!'
  TimeEightAM: '&7Time Changed To &e8AM&7!'
  TimeNineAM: '&7Time Changed To &e9AM&7!'
  TimeTenAM: '&7Time Changed To &e10AM&7!'
  TimeElevenAM: '&7Time Changed To &e11AM&7!'
  TimeTwelvePM: '&7Time Changed To &e12PM&7!'
  TimeOnePM: '&7Time Changed To &e1PM&7!'
  TimeTwoPM: '&7Time Changed To &e2PM&7!'
  TimeThreePM: '&7Time Changed To &e3PM&7!'
  TimeFourPM: '&7Time Changed To &e4PM&7!'
  TimeFivePM: '&7Time Changed To &e5PM&7!'
  TimeSixPM: '&7Time Changed To &e6PM&7!'
  TimeSevenPM: '&7Time Changed To &e7PM&7!'
  TimeEightPM: '&7Time Changed To &e8PM&7!'
  TimeNinePM: '&7Time Changed To &e9PM&7!'
  TimeTenPM: '&7Time Changed To &e10PM&7!'
  TimeElevenPM: '&7Time Changed To &e11PM&7!'
  TimeTwelveAM: '&7Time Changed To &e12AM&7!'
  TimeOneAM: '&7Time Changed To &e1AM&7!'
  TimeTwoAM: '&7Time Changed To &e2AM&7!'
  TimeThreeAM: '&7Time Changed To &e3AM&7!'
  TimeFourAM: '&7Time Changed To &e4AM&7!'
  TimeFiveAM: '&7Time Changed To &e5AM&7!'
#=======================================================
#Tools Menu Messages 
#Permission: ustaffmode.tools
  ToolsMenu: '&7Opened The Tools Menu!'  
#FlyMenu
  FlyMenu: '&7Opened The Fly Menu!'      
  FlyON: '&7Toggled Fly &aON&7!'
  FlyOFF: '&7Toggled Fly &cOFF&7!'
#VanishMenu
  VanishMenu: '&7Opened The Vanish Menu!' 
  VanishON: '&7Vanish & Fly &a&lEnabled!'
  VanishOFF: '&7Vanish & Fly &c&lDisabled!'
#HealAndFeedMenu
  FeedAndHealMenu: '&7Opened The Feed + Heal Menu!' 
  Heal: '&7You got healed!'
  Feed: '&7Yum!! That was some good food!'
#Other Tools
  ClearChat: '&7Chat Cleared!' 
  ClearInv: '&7Inventory Cleared!'
#=======================================================
#AdminItems Menu Messages  
#Permission: ustaffmode.adminitems 
  AdminItemMenu: '&7Opened The Admin Items Menu!'
  AdminSword: '&7You received a &c&lADMIN &7sword!'
  AdminBow: '&7You received a &c&lADMIN &7bow!'
  AdminStick: '&7You received a &c&lADMIN &7stick!'
#=======================================================
#Server Manager Menu Messages  
#Permission: ustaffmode.servermanager
  ServerManagerMenu: '&7Opened The Server Manager Menu!'
  WeatherRain: '&7Weather Turned To Rain!'
  WeatherClear: '&7Weather Turned To Clear!'
  WhitelistON: '&7Whitelist Turned &eON&7!'
  WhitelistOFF: '&7Whitelist Turned &cOFF&7!'  
#=======================================================
#Effects Menu Messages    
#Permission: ustaffmode.effects
  EffectsMenu: '&7Opened The Effect Menu!'   
  EffectsClear: '&7Effects Cleared!'
  SpeedMenu: '&7Opened Speed Effect Menu!'
  JumpMenu: '&7Opened Jump Effect Menu!'
  StrengthMenu: '&7Opened Strength Effect Menu!'
  Speed1: '&7Speed-1 Applied For &cFOREVER!'
  Speed2: '&7Speed-2 Applied For &cFOREVER!'
  Speed3: '&7Speed-3 Applied For &cFOREVER!'
  Speed4: '&7Speed-4 Applied For &cFOREVER!'
  Speed5: '&7Speed-5 Applied For &cFOREVER!'
  Speed6: '&7Speed-6 Applied For &cFOREVER!'
  Speed7: '&7Speed-7 Applied For &cFOREVER!'
  Speed8: '&7Speed-8 Applied For &cFOREVER!'
  Jump1: '&7Jump-1 Applied For &cFOREVER!'
  Jump2: '&7Jump-2 Applied For &cFOREVER!'
  Jump3: '&7Jump-3 Applied For &cFOREVER!'
  Jump4: '&7Jump-4 Applied For &cFOREVER!'
  Jump5: '&7Jump-5 Applied For &cFOREVER!'
  Jump6: '&7Jump-6 Applied For &cFOREVER!'
  Jump7: '&7Jump-7 Applied For &cFOREVER!'
  Jump8: '&7Jump-8 Applied For &cFOREVER!'
  Strength1: '&7Strength-1 Applied For &cFOREVER!'
  Strength2: '&7Strength-2 Applied For &cFOREVER!'
  Strength3: '&7Strength-3 Applied For &cFOREVER!'
  Strength4: '&7Strength-4 Applied For &cFOREVER!'
  Strength5: '&7Strength-5 Applied For &cFOREVER!'
  Strength6: '&7Strength-6 Applied For &cFOREVER!'
  Strength7: '&7Strength-7 Applied For &cFOREVER!'
  Strength8: '&7Strength-8 Applied For &cFOREVER!'
  Invisibility: '&7Invisibility Applied For &cFOREVER!'
  WatherBreathing: '&7Water Breathing Applied For &cFOREVER!'
  NightVision: '&7Night Vision Applied For &cFOREVER!'
  Slowness: '&7Slowness Applied For &cFOREVER!'
#=======================================================
#Mob Menu Messages    
#Permission: ustaffmode.mobs 
  MobMenu: '&7Opened The Mob Menu!'
  ExtraMobMenu: '&7Opened Extra Mob Menu!'
  SpawnCreeper: '&7Spawned Creeper!'  
  SpawnSkeleton: '&7Spawned Skeleton!'
  SpawnSpider: '&7Spawned Spider!'
  SpawnZombie: '&7Spawned Zombie!'
  SpawnSlime: '&7Spawned Slime!'
  SpawnGhast: '&7Spawned Ghast!'
  SpawnZombiePig: '&7Spawned Zombie Pigman!'
  SpawnEnderman: '&7Spawned Enderman!'
  SpawnCaveSpider: '&7Spawned CaveSpider!'
  SpawnSilverfish: '&7Spawned Silverfish!'
  SpawnBlaze: '&7Spawned Blaze!'
  SpawnMagmaCube: '&7Spawned Magma Cube!'
  SpawnBat: '&7Spawned Bat!'
  SpawnWitch: '&7Spawned Witch!'
  SpawnPig: '&7Spawned Pig!'
  SpawnSheep: '&7Spawned Sheep!'
  SpawnCow: '&7Spawned Cow!'
  SpawnChicken: '&7Spawned Chicken!'
  SpawnSquid: '&7Spawned Squid!'
  SpawnWolf: '&7Spawned Wolf!'
  SpawnMushroom: '&7Spawned Mushroom!'
  SpawnOcelot: '&7Spawned Ocelot!'
  SpawnHorse: '&7Spawned Horse!'
  SpawnVillager: '&7Spawned Villager!'
  SpawnRabbit: '&7Spawned Rabbit!'
#Other Mobs Menu
  SpawnIronGolem: '&7Spawned IronGolem!'
  SpawnSnowGolem: '&7Spawned SnowGolem!'
  SpawnGuardian: '&7Spawned Guardian!'
  SpawnGiant: '&cSpawned Giant!'
  SpawnWither: '&cSpawned Wither!'
  SpawnEnderDragon: '&cSpawned EnderDragon!'
#=======================================================
#Difficulty Menu Messages   
#Permission: ustaffmode.difficulty
  DifficultyMenu: '&7Opened The Difficulty Menu!'
  DifficultyPeace: '&7Difficulty set to Peaceful!'
  DifficultyEasy: '&7Difficulty set to Easy!'
  DifficultyNormal: '&7Difficulty set to Normal!'
  DifficultyHard: '&7Difficulty set to Hard!'
#=======================================================
#Troll Menu Messages 
#Permission: ustaffmode.trolls
  TrollMenu: '&7Opened The Troll Menu!'
  CowTroll: '&7Spawned cow on all players!'
  CowTrollPlayer: '&cYou were hit with a flying cow!'
  LightningTroll: '&7Spawned lightning strike on all players!'
  LightningTrollPlayer: '&cYou were hit with a lightning strike!' 
  BlindnessTroll: '&7Gave all players blindness for &c&l&oFOREVER!'
  BlindnessTrollPlayer: '&cYou were given blindness &c&l&oFOREVER!' 
  SlownessTroll: '&7Gave all players slowness &c&l&oFOREVER!'
  SlownessTrollPlayer: '&cYou were given slowness &c&l&oFOREVER!'
  NauseaTroll: '&7Gave all players nausea &c&l&oFOREVER!'
  NauseaTrollPlayer: '&cYou were given nausea for &c&l&oFOREVER!'
  JumpTroll: '&7Gave all players jump boost &c&l&oFOREVER!'
  JumpTrollPlayer: '&cYou were given jump boost &c&l&oFOREVER!'
  WeaknessTroll: '&7Gave all players weakness &c&l&oFOREVER!'
  WeaknessTrollPlayer: '&cYou were given weakness boost &c&l&oFOREVER!'
#======================================================= 
#Mob Manager Menu Messages
#Permission: ustaffmode.mobmanager
  MobManagerMenu: '&7Opened The Mob Manager Menu!'
  MobClear: '&7Cleared all mobs!'
#=======================================================      
