name: UltimateStaffMode
# Change to 5.1 if not using Maven
version: ${project.version}
main: me.refrac.staff.Main
api-version: 1.13
authors: [Refrac, BGHDDevelopment(Noodles)]
# Change to UltimateStaffMode StaffGUI Utilities if not using Maven
description: ${project.description}
commands:
  staffmode:
    description: Main Command
    aliases: [sg, staffgui, sm]
