main: me.zachstyles.staff.Main
name: UltimateStaffMode
version: 3.4
depend: [ProtocolLib]
softdepend: [DeluxeMenus]
load: STARTUP
authors: [Zachstyles, BGHDDevelopment(Noodles)]
Website: https://www.spigotmc.org/resources/ultimatestaffmode-1-8-1-12.54528/

commands: 
   staffmode:
      description: UltimateStaffMode
      aliases: [sg, staffgui]
