main: me.refrac.staff.Main
name: UltimateStaffMode
version: 4.2
depend: [ProtocolLib]
softdepend: [DeluxeMenus]
load: STARTUP
authors: [Refrac, BGHDDevelopment(Noodles)]
Website: https://www.spigotmc.org/resources/54528/

commands: 
   staffmode:
      description: UltimateStaffMode
      aliases: [sg, staffgui]
